server:
  port: 8070
spring:
  cloud:
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: 192.168.9.227:9876
        bindings:
          in-order-alter: {consumer.orderly: true}  #是否排序
          in-push-depth: {consumer.broadcasting: true} #是否广播
      bindings:
        out-new-order: 
          destination: new-order-topic
          content-type: application/json
        out-cancel-order: 
          destination: cancel-order-topic
          content-type: application/json
        in-order-alter: 
          destination: order-alter-topic
          group: service-order
        in-new-trade: 
          destination: new-trade-topic
          group: service-trade
        in-push-depth: 
          destination: push-depth-topic
          group: service-depth
